// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package checkpoint

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "checkpoint", asset.ModuleFieldsPri, AssetCheckpoint); err != nil {
		panic(err)
	}
}

// AssetCheckpoint returns asset data.
// This is the base64 encoded gzipped contents of module/checkpoint.
func AssetCheckpoint() string {
	return "eJxsjTEKwzAQBHu9Yj/gPOCKNIF0eUSQzs5hWXdI58K/DzYOiOAtd5eZATNvhPjhOJtK8QC4eGbCo+8St1jFXLQQ7gFAt+Olac0cgFE4p0bHPqC8F/5j7/HNmDBVXe1sLuh7ngcNY9Wlt2Wd2u08/YTfAAAA///OIT14"
}
