// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package checkpoint

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "checkpoint", asset.ModuleFieldsPri, AssetCheckpoint); err != nil {
		panic(err)
	}
}

// AssetCheckpoint returns asset data.
// This is the base64 encoded gzipped contents of module/checkpoint.
func AssetCheckpoint() string {
	return "eJxsjTEKwzAQBHu9Yj/gPOCKNIF0eUSQzs5hWXdI58K/DzYOiOAtd5eZATNvhPjhOJtK8QC4eGbCo+8St1jFXLQQ7gFAt+Olac0cgFE4p0bHPqC8F/5j7/HNmDBVXe1sLuh7ngcNY9Wlt2Wd2u08/YTfAAAA///OIT14"
}
